import '../css/water.css'
import '../css/globals.css'
import { Literata } from 'next/font/google'

import Header from '../components/header/Header'

const literata = Literata({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={literata.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
